import json
import os
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

INVESTIGATION_DIR = (
    PROJECT_ROOT
    / "reports"
    / "investigation"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "ai_investigation"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv(
    PROJECT_ROOT / ".env"
)


# ============================================================
# LLM CONFIGURATION
# ============================================================

MODEL_NAME = os.getenv(
    "RAZORGUARD_LLM_MODEL",
    "gpt-5-mini",
)

MAX_OUTPUT_TOKENS = 1200


# ============================================================
# CASE LOADING
# ============================================================

def load_investigation_case(
    transaction_id: int,
) -> dict:
    """
    Load a previously generated investigation case.
    """

    case_path = (
        INVESTIGATION_DIR
        / f"case_{transaction_id}.json"
    )

    if not case_path.exists():
        raise FileNotFoundError(
            f"Investigation case not found: "
            f"{case_path}"
        )

    with open(
        case_path,
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(file)


# ============================================================
# PROMPT CONSTRUCTION
# ============================================================

def build_system_prompt() -> str:
    """
    System instructions for the fraud investigation
    LLM.

    The model is explicitly restricted to the evidence
    generated by RazorGuard.
    """

    return """
You are RazorGuard AI, an AI-assisted financial
fraud investigation analyst.

Your role is to interpret structured evidence
generated by a fraud detection system.

IMPORTANT SAFETY AND GROUNDING RULES:

1. Use ONLY the evidence contained in the
   investigation case provided by the application.

2. Never invent customer history.

3. Never invent previous transactions.

4. Never invent geographic information.

5. Never invent device history.

6. Never invent financial losses.

7. Never invent external fraud intelligence.

8. SHAP values represent model contributions.
   They do NOT prove that a feature caused fraud.

9. Do not change the fraud probability produced
   by the ML model.

10. Do not change the risk level produced by the
    Risk Engine.

11. Do not change the decision produced by the
    Risk Engine.

12. If information is unavailable, explicitly
    state that it is unavailable.

13. Clearly distinguish model evidence from
    business policy.

14. Do not claim certainty about fraudulent intent.

15. Produce concise, professional output suitable
    for a fraud analyst.

Return the investigation using exactly these
sections:

1. Executive Assessment
2. Model Evidence
3. Risk-Reducing Evidence
4. Decision
5. Recommended Action
6. Investigation Limitations
"""


def build_case_prompt(
    case: dict,
) -> str:
    """
    Convert the structured case into a tightly
    controlled LLM input.
    """

    risk_factors = json.dumps(
        case[
            "top_risk_factors"
        ],
        indent=2,
    )

    reducing_factors = json.dumps(
        case[
            "top_risk_reducing_factors"
        ],
        indent=2,
    )

    return f"""
Analyze the following RazorGuard investigation case.

TRANSACTION
-----------
Transaction ID:
{case["transaction_id"]}

ACTUAL LABEL
------------
{case["actual_label"]}

MODEL OUTPUT
------------
Fraud Probability:
{case["fraud_probability"]}

Risk Score:
{case["risk_score"]}

Risk Level:
{case["risk_level"]}

Decision:
{case["decision"]}

Model Version:
{case["model_version"]}

Threshold Version:
{case["threshold_version"]}

TOP RISK-INCREASING MODEL CONTRIBUTIONS
---------------------------------------

{risk_factors}

TOP RISK-REDUCING MODEL CONTRIBUTIONS
-------------------------------------

{reducing_factors}

Now produce the investigation report according
to the system instructions.

Important:
- Preserve the probability exactly.
- Preserve the risk level exactly.
- Preserve the decision exactly.
- Do not invent missing information.
- Treat SHAP values as model contributions.
"""


# ============================================================
# LLM CALL
# ============================================================

def generate_llm_report(
    case: dict,
) -> str:
    """
    Send the structured investigation case to the LLM.
    """

    api_key = os.getenv(
        "OPENAI_API_KEY"
    )

    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not configured. "
            "Add it to the .env file."
        )

    client = OpenAI(
        api_key=api_key
    )

    system_prompt = (
        build_system_prompt()
    )

    user_prompt = (
        build_case_prompt(
            case
        )
    )

    response = client.responses.create(
        model=MODEL_NAME,
        instructions=system_prompt,
        input=user_prompt,
        max_output_tokens=MAX_OUTPUT_TOKENS,
    )

    return response.output_text


# ============================================================
# SAVE REPORT
# ============================================================

def save_report(
    transaction_id: int,
    report: str,
) -> Path:
    """
    Save the generated AI investigation report.
    """

    output_path = (
        OUTPUT_DIR
        / f"case_{transaction_id}_llm_report.txt"
    )

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as file:

        file.write(
            report.strip()
        )

    return output_path


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    print(
        "=" * 70
    )

    print(
        "RazorGuard AI - LLM Investigation Agent"
    )

    print(
        "=" * 70
    )

    # --------------------------------------------------------
    # Demo cases
    # --------------------------------------------------------

    transaction_ids = [
        3444522,
        3427568,
    ]

    for transaction_id in transaction_ids:

        print(
            "\n" + "=" * 70
        )

        print(
            f"Investigating transaction "
            f"{transaction_id}"
        )

        print(
            "=" * 70
        )

        # ----------------------------------------------------
        # Load case
        # ----------------------------------------------------

        print(
            "\nLoading investigation case..."
        )

        case = load_investigation_case(
            transaction_id
        )

        print(
            "Investigation case loaded."
        )

        print(
            f"Fraud probability: "
            f"{case['fraud_probability']:.6f}"
        )

        print(
            f"Risk level: "
            f"{case['risk_level']}"
        )

        print(
            f"Decision: "
            f"{case['decision']}"
        )

        # ----------------------------------------------------
        # Generate report
        # ----------------------------------------------------

        print(
            "\nCalling LLM investigator..."
        )

        report = generate_llm_report(
            case
        )

        # ----------------------------------------------------
        # Display
        # ----------------------------------------------------

        print(
            "\n" + "=" * 70
        )

        print(
            "AI INVESTIGATION REPORT"
        )

        print(
            "=" * 70
        )

        print(
            "\n"
            + report
        )

        # ----------------------------------------------------
        # Save
        # ----------------------------------------------------

        output_path = save_report(
            transaction_id,
            report,
        )

        print(
            "\nReport saved to:"
        )

        print(
            output_path
        )

    # --------------------------------------------------------
    # Complete
    # --------------------------------------------------------

    print(
        "\n" + "=" * 70
    )

    print(
        "LLM INVESTIGATION COMPLETE"
    )

    print(
        "=" * 70
    )


if __name__ == "__main__":
    main()
